apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-demo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-demo-server
  template:
    metadata:
      labels:
        app: stats-demo-server
    spec:
      containers:
        - name: stats-demo-server
          image: stats-demo-server
          ports:
            - containerPort: 3001 
